version: "3"
services:
    nginx:
        image: nginx:1.15
        restart: always
        container_name: nginx
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
        ports:
            - 8080:80
        environment:
            - NGINX_HOST=localhost
            - NGINX_PORT=80
    node:
        image: node:10.16.0-alpine
        restart: always
        container_name: node
        volumes:
            - ./node:/src
        ports:
            - 3000:3000
        working_dir: /src
        depends_on:
            - mongo
        command: [sh, -c, npm install && npm start]
    mongo:
        image: mongo:4.0.10
        restart: always
        container_name: mongo
        ports:
            - 27017:27017
        volumes:
            - ./db:/data/db

